test_parameters_kmers <- function()
{
    data(metaboExp1)
    data(metaboExp2)
    obs <- tryCatch(runMetaboCombiner(list(metaboExp1, metaboExp2), algorithm = "kmer", trunc = -10), error=conditionMessage)
    checkIdentical("trunc parameter must be > 0!", obs)
    obs <- tryCatch(runMetaboCombiner(list(metaboExp1, metaboExp2), algorithm = "kmer", abs = -10), error=conditionMessage)
    checkIdentical("abs parameter must be > 0!", obs)
    obs <- tryCatch(runMetaboCombiner(list(metaboExp1, metaboExp2), algorithm = "kmer", ppm = -10), error=conditionMessage)
    checkIdentical("ppm parameter must be > 0!", obs)
    obs <- tryCatch(runMetaboCombiner(list(metaboExp1, metaboExp2), algorithm = "kmer", trunc = -1), error=conditionMessage)
    checkIdentical("At least one of ppm, abs, or trunc parameters must be set up correctly!", obs)
    obs <- tryCatch(runMetaboCombiner(list(metaboExp1, metaboExp2), algorithm = "kmer", abs = -1), error=conditionMessage)
    checkIdentical("At least one of ppm, abs, or trunc parameters must be set up correctly!", obs)
    obs <- tryCatch(runMetaboCombiner(list(metaboExp1, metaboExp2), algorithm = "kmer", ppm = -1), error=conditionMessage)
    checkIdentical("At least one of ppm, abs, or trunc parameters must be set up correctly!", obs)
    
    obs <- tryCatch(runMetaboCombiner(list(metaboExp1, metaboExp2), algorithm = "kmer", trunc = "123"), error=conditionMessage)
    checkIdentical("ppm, abs, and trunc parameters must be numeric!", obs)
    obs <- tryCatch(runMetaboCombiner(list(metaboExp1, metaboExp2), algorithm = "kmer", abs = "123"), error=conditionMessage)
    checkIdentical("ppm, abs, and trunc parameters must be numeric!", obs)
    obs <- tryCatch(runMetaboCombiner(list(metaboExp1, metaboExp2), algorithm = "kmer", ppm = "123"), error=conditionMessage)
    checkIdentical("ppm, abs, and trunc parameters must be numeric!", obs)
    
    obs <- tryCatch(runMetaboCombiner(list(metaboExp1, metaboExp2), algorithm = "kmer"), error=conditionMessage)
    checkIdentical("At least one of ppm, abs, or trunc parameters must be set up correctly!", obs)
    obs <- tryCatch(runMetaboCombiner(list(metaboExp1, metaboExp2)), error=conditionMessage)
    checkIdentical("At least one of ppm, abs, or trunc parameters must be set up correctly!", obs)
    obs <- tryCatch(runMetaboCombiner(list(metaboExp1, metaboExp2), algorithm = "kmer", trunc = 2, abs = 0.01, ppm = 20), error=conditionMessage)
    checkIdentical("Only one parameter of ppm, abs, or trunc can be set up!", obs)
}

test_parameters_rtcor <- function()
{
    data(metaboExp1)
    data(metaboExp2)
    obs <- tryCatch(runMetaboCombiner(list(metaboExp1, metaboExp2), algorithm = "rtcor", trunc = -10), error=conditionMessage)
    checkIdentical("trunc parameter must be > 0!", obs)
    obs <- tryCatch(runMetaboCombiner(list(metaboExp1, metaboExp2), algorithm = "rtcor", abs = -10), error=conditionMessage)
    checkIdentical("abs parameter must be > 0!", obs)
    obs <- tryCatch(runMetaboCombiner(list(metaboExp1, metaboExp2), algorithm = "rtcor", ppm = -10), error=conditionMessage)
    checkIdentical("ppm parameter must be > 0!", obs)
    obs <- tryCatch(runMetaboCombiner(list(metaboExp1, metaboExp2), algorithm = "rtcor", trunc = -1), error=conditionMessage)
    checkIdentical("At least one of ppm, abs, or trunc parameters must be set up correctly!", obs)
    obs <- tryCatch(runMetaboCombiner(list(metaboExp1, metaboExp2), algorithm = "rtcor", abs = -1), error=conditionMessage)
    checkIdentical("At least one of ppm, abs, or trunc parameters must be set up correctly!", obs)
    obs <- tryCatch(runMetaboCombiner(list(metaboExp1, metaboExp2), algorithm = "rtcor", ppm = -1), error=conditionMessage)
    checkIdentical("At least one of ppm, abs, or trunc parameters must be set up correctly!", obs)
    
    obs <- tryCatch(runMetaboCombiner(list(metaboExp1, metaboExp2), algorithm = "rtcor", trunc = "123"), error=conditionMessage)
    checkIdentical("ppm, abs, and trunc parameters must be numeric!", obs)
    obs <- tryCatch(runMetaboCombiner(list(metaboExp1, metaboExp2), algorithm = "rtcor", abs = "123"), error=conditionMessage)
    checkIdentical("ppm, abs, and trunc parameters must be numeric!", obs)
    obs <- tryCatch(runMetaboCombiner(list(metaboExp1, metaboExp2), algorithm = "rtcor", ppm = "123"), error=conditionMessage)
    checkIdentical("ppm, abs, and trunc parameters must be numeric!", obs)
    
    obs <- tryCatch(runMetaboCombiner(list(metaboExp1, metaboExp2), algorithm = "rtcor"), error=conditionMessage)
    checkIdentical("At least one of ppm, abs, or trunc parameters must be set up correctly!", obs)
    obs <- tryCatch(runMetaboCombiner(list(metaboExp1, metaboExp2)), error=conditionMessage)
    checkIdentical("At least one of ppm, abs, or trunc parameters must be set up correctly!", obs)
    obs <- tryCatch(runMetaboCombiner(list(metaboExp1, metaboExp2), algorithm = "rtcor", trunc = 2, abs = 0.01, ppm = 20), error=conditionMessage)
    checkIdentical("Only one parameter of ppm, abs, or trunc can be set up!", obs)
}